POST http://localhost:8080/products/
Content-Type: application/json

{
  "name": "apple",
  "price": "1.23",
  "category": "name"
}

###
GET http://localhost:8080/products/

###
POST http://localhost:8080/category/
Content-Type: application/json

{
  "name": "aa"
}
###
DELETE http://localhost:8080/category/1

###
GET http://localhost:8080/products/search?page=0&size=6&q=&sort=description&direction=DESC