<!DOCTYPE html>
<html lang="ru">
  <head>
    <title>404</title>
    <link rel="stylesheet" href="/static/css/main.css" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
      crossorigin="anonymous"
    />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700;900&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    <nav class="navbar navbar-light px-5">
      <div class="container">
        <span class="user__nav__brand">MyShop</span>
        <div class="user__nav">
          <div class="user__nav__name">
            <span>Welcome</span>
            <b>Name</b>
          </div>
          <div class="user__nav__links d-flex">
            <a href="active">My profile</a>
            <a href="">Logout</a>
            <a href="">Log-in</a>
          </div>
        </div>
      </div>
    </nav>
    <main>
      <div class="content container">
        <div class="notfound">
            <div class="block">
                <div class="hit-the-floor">404</div>
                <p>Произошла ошибочка</p>
            </div>
        </div>
      </div>
    </main>
  </body>
</html>
